import { BaseResource, BaseResponse } from '../../shared/infrastructure/base-response';
import { WeekDay } from '../domain/model/activity.entity';

/**
 * Represents a single activity resource as returned by the backend API.
 * Maps directly to the JSON shape of the /activities endpoint response.
 */
export interface ActivityResource extends BaseResource {
  /** Unique identifier generated by the backend */
  id: number;
  /** ID of the resident this activity is assigned to */
  residentId: number;
  /** ID of the healthcare staff member responsible for execution */
  healthcareStaffId: number;
  /** Activity category type as a raw string from the API */
  type: string;
  /** Descriptive title of the activity (e.g. "Morning bath") */
  title: string;
  /** Current lifecycle status as a raw string from the API */
  status: string;
  /** Whether this activity repeats on a weekly schedule */
  isRecurring: boolean;
  /** Days of the week on which the activity recurs */
  recurringDays: WeekDay[];
}

/**
 * Represents the full response envelope from GET /activities.
 */
export interface ActivitiesResponse extends BaseResponse {
  activities: ActivityResource[];
}
