import { BaseEntity } from '../../../shared/domain/model/base-entity';

/**
 * Represents the type of care or recreational activity.
 * - MEAL: Feeding and nutrition care
 * - BATH: Hygiene and bathing care
 * - RISK_PROFILE: Medical risk assessment
 * - RECREATIONAL: Leisure and social activities
 */
export type ActivityType = 'MEAL' | 'BATH' | 'RISK_PROFILE' | 'RECREATIONAL';

/**
 * Represents the lifecycle status of an activity.
 * - PENDING: Created by admin, not yet started
 * - IN_PROGRESS: Currently being executed by staff
 * - COMPLETED: Finished and confirmed by staff
 */
export type ActivityStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';

/**
 * Represents the days of the week for recurring activities.
 */
export type WeekDay = 'MON' | 'TUE' | 'WED' | 'THU' | 'FRI' | 'SAT' | 'SUN';

/**
 * Activity aggregate root for the Activities bounded context.
 *
 * Represents a care or recreational activity assigned to a resident
 * within a nursing home. Activities are created and managed by
 * administrators via the web platform, and executed and completed
 * by healthcare staff via the mobile application.
 *
 * Lifecycle:
 * ```
 * Admin creates → PENDING
 * Staff starts  → IN_PROGRESS  (via log())
 * Staff finishes → COMPLETED   (via complete())
 * ```
 *
 * @implements {BaseEntity}
 */
export class Activity implements BaseEntity {
  /** Unique identifier generated by the backend */
  private _id: number;

  /** ID of the resident this activity is assigned to */
  private _residentId: number;

  /** ID of the healthcare staff member responsible for execution */
  private _healthcareStaffId: number;

  /** Category of the activity */
  private _type: ActivityType;

  /** Human-readable name describing the activity (e.g. "Morning bath") */
  private _title: string;

  /** Current lifecycle status */
  private _status: ActivityStatus;

  /** Whether this activity repeats on a weekly schedule */
  private _isRecurring: boolean;

  /** Days of the week on which the activity recurs. Empty if not recurring. */
  private _recurringDays: WeekDay[];

  /**
   * Creates a new Activity instance.
   * @param activity - Plain object with all required activity fields
   */
  constructor(activity: {
    id: number;
    residentId: number;
    healthcareStaffId: number;
    type: ActivityType;
    title: string;
    status: ActivityStatus;
    isRecurring: boolean;
    recurringDays: WeekDay[];
  }) {
    this._id = activity.id;
    this._residentId = activity.residentId;
    this._healthcareStaffId = activity.healthcareStaffId;
    this._type = activity.type;
    this._title = activity.title;
    this._status = activity.status;
    this._isRecurring = activity.isRecurring;
    this._recurringDays = activity.recurringDays;
  }

  // ─── Getters ────────────────────────────────────────────────────────────────

  /** @returns The unique identifier of the activity */
  get id(): number { return this._id; }

  /** @returns The ID of the assigned resident */
  get residentId(): number { return this._residentId; }

  /** @returns The ID of the responsible healthcare staff member */
  get healthcareStaffId(): number { return this._healthcareStaffId; }

  /** @returns The activity category type */
  get type(): ActivityType { return this._type; }

  /** @returns The descriptive title of the activity */
  get title(): string { return this._title; }

  /** @returns The current lifecycle status */
  get status(): ActivityStatus { return this._status; }

  /** @returns Whether the activity is set to recur weekly */
  get isRecurring(): boolean { return this._isRecurring; }

  /** @returns The days of the week on which the activity recurs */
  get recurringDays(): WeekDay[] {
    if (!Array.isArray(this._recurringDays)) return [];
    return (this._recurringDays as unknown[]).filter(d => d !== null && d !== undefined && d !== '') as WeekDay[];
  }
  // ─── Setters (admin-editable fields only) ───────────────────────────────────

  /**
   * Updates the activity category.
   * @param value - New activity type
   */
  set type(value: ActivityType) { this._type = value; }

  /**
   * Updates the descriptive title of the activity.
   * @param value - New title string
   */
  set title(value: string) { this._title = value; }

  /**
   * Enables or disables weekly recurrence.
   * @param value - True to enable recurrence
   */
  set isRecurring(value: boolean) { this._isRecurring = value; }

  /**
   * Updates the days on which the activity recurs.
   * @param value - Array of week days
   */
  set recurringDays(value: WeekDay[]) {
    this._recurringDays = Array.isArray(value)
      ? (value as unknown[]).filter(d => d !== null && d !== undefined && d !== '') as WeekDay[]
      : [];
  }

  // ─── Domain methods ─────────────────────────────────────────────────────────

  /**
   * Transitions the activity to IN_PROGRESS status.
   * Called by healthcare staff when starting the activity.
   * @returns The updated Activity instance
   */
  log(): Activity {
    this._status = 'IN_PROGRESS';
    return this;
  }

  /**
   * Transitions the activity to COMPLETED status.
   * Called by healthcare staff upon finishing the activity.
   * @returns The updated Activity instance
   */
  complete(): Activity {
    this._status = 'COMPLETED';
    return this;
  }

  /**
   * Checks whether the activity has been completed.
   * Used by the UI to disable or hide the complete action.
   * @returns True if status is COMPLETED
   */
  isCompleted(): boolean {
    return this._status === 'COMPLETED';
  }

  /**
   * Checks whether the activity is still pending execution.
   * Used by the UI to determine initial state display.
   * @returns True if status is PENDING
   */
  isPending(): boolean {
    return this._status === 'PENDING';
  }
}
