/**
 * scripts/generate-fcm-sw.js
 * ---------------------------------------------------------------------------
 * Generates public/firebase-messaging-sw.js from environment variables.
 * Run this BEFORE `ng build` in CI/CD pipelines (e.g. Cloudflare Pages).
 *
 * Required environment variables:
 *   FIREBASE_API_KEY
 *   FIREBASE_AUTH_DOMAIN
 *   FIREBASE_PROJECT_ID
 *   FIREBASE_STORAGE_BUCKET
 *   FIREBASE_MESSAGING_SENDER_ID
 *   FIREBASE_APP_ID
 *
 * Optional:
 *   FIREBASE_SDK_VERSION   (default: 10.12.0)
 *
 * Cloudflare Pages build command:
 *   node scripts/generate-fcm-sw.js && ng build
 *
 * Local usage (bash):
 *   FIREBASE_API_KEY=xxx FIREBASE_PROJECT_ID=yyy node scripts/generate-fcm-sw.js
 * ---------------------------------------------------------------------------
 */

'use strict';

const fs = require('fs');
const path = require('path');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
];

const missing = required.filter(key => !process.env[key]);
if (missing.length > 0) {
  console.warn('[generate-fcm-sw] Missing environment variables:', missing.join(', '));
  console.warn('[generate-fcm-sw] Keeping existing public/firebase-messaging-sw.js unchanged.');
  process.exit(0);
}

const sdkVersion = process.env.FIREBASE_SDK_VERSION || '10.12.0';

const config = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID,
};

const content = `/* Auto-generated by scripts/generate-fcm-sw.js — do not edit manually */
importScripts('https://www.gstatic.com/firebasejs/${sdkVersion}/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/${sdkVersion}/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage(function (payload) {
  const title = payload.notification?.title ?? 'Veyra';
  const body = payload.notification?.body ?? '';
  const icon = payload.notification?.icon ?? '/images/shared/logo.png';

  return self.registration.showNotification(title, {
    body,
    icon,
    badge: '/images/shared/logo.png',
    data: payload.data ?? {},
    tag: payload.data?.tag ?? 'veyra-notification',
  });
});
`;

const outPath = path.join(__dirname, '..', 'public', 'firebase-messaging-sw.js');
fs.writeFileSync(outPath, content, 'utf-8');
console.log('[generate-fcm-sw] Written to', outPath);
