import { BaseEntity } from '../../../shared/domain/model/base-entity';

export type AlertSeverity = 'URGENT' | 'WARNING' | 'INFO';
export type AlertType = 'VITAL_SIGNS' | 'TELEMETRY' | 'MEDICATION' | 'FALL_RISK' | 'GENERAL';
export type AlertSource = 'STAFF' | 'SYSTEM' | 'IOT';
export type AlertStatus = 'UNREAD' | 'READ' | 'ACKNOWLEDGED';

/**
 * Alert entity representing a care alert generated by staff or IoT devices
 * within the scope of a nursing home.
 * Acts as the Aggregate Root for the Alerts bounded context.
 */
export class Alert implements BaseEntity {
  private _id: number;
  private _nursingHomeId: number;
  private _residentId: number;
  private _residentName: string;
  private _roomNumber: string;
  private _title: string;
  private _description: string;
  private _severity: AlertSeverity;
  private _type: AlertType;
  private _source: AlertSource;
  private _status: AlertStatus;
  private _reportedBy: string;
  private _createdAt: string;

  constructor(alert: {
    id: number;
    nursingHomeId: number;
    residentId: number;
    residentName: string;
    roomNumber: string;
    title: string;
    description: string;
    severity: AlertSeverity;
    type: AlertType;
    source: AlertSource;
    status: AlertStatus;
    reportedBy: string;
    createdAt: string;
  }) {
    this._id = alert.id;
    this._nursingHomeId = alert.nursingHomeId;
    this._residentId = alert.residentId;
    this._residentName = alert.residentName;
    this._roomNumber = alert.roomNumber;
    this._title = alert.title;
    this._description = alert.description;
    this._severity = alert.severity;
    this._type = alert.type;
    this._source = alert.source;
    this._status = alert.status;
    this._reportedBy = alert.reportedBy;
    this._createdAt = alert.createdAt;
  }

  get id(): number { return this._id; }
  set id(value: number) { this._id = value; }

  get nursingHomeId(): number { return this._nursingHomeId; }
  set nursingHomeId(value: number) { this._nursingHomeId = value; }

  get residentId(): number { return this._residentId; }
  set residentId(value: number) { this._residentId = value; }

  get residentName(): string { return this._residentName; }
  set residentName(value: string) { this._residentName = value; }

  get roomNumber(): string { return this._roomNumber; }
  set roomNumber(value: string) { this._roomNumber = value; }

  get title(): string { return this._title; }
  set title(value: string) { this._title = value; }

  get description(): string { return this._description; }
  set description(value: string) { this._description = value; }

  get severity(): AlertSeverity { return this._severity; }
  set severity(value: AlertSeverity) { this._severity = value; }

  get type(): AlertType { return this._type; }
  set type(value: AlertType) { this._type = value; }

  get source(): AlertSource { return this._source; }
  set source(value: AlertSource) { this._source = value; }

  get status(): AlertStatus { return this._status; }
  set status(value: AlertStatus) { this._status = value; }

  get reportedBy(): string { return this._reportedBy; }
  set reportedBy(value: string) { this._reportedBy = value; }

  get createdAt(): string { return this._createdAt; }
  set createdAt(value: string) { this._createdAt = value; }

  /** Marks the alert as acknowledged. */
  acknowledge(): Alert {
    this._status = 'ACKNOWLEDGED';
    return this;
  }

  /** Marks the alert as read. */
  markAsRead(): Alert {
    if (this._status === 'UNREAD') {
      this._status = 'READ';
    }
    return this;
  }

  get isUnread(): boolean {
    return this._status === 'UNREAD';
  }

  get isCritical(): boolean {
    return this._severity === 'URGENT';
  }
}
